"""
Mapeo de nombres abreviados (football-data.co.uk) a nombres completos.

football-data.co.uk usa nombres cortos como "Man United", "Ath Madrid", "M'gladbach".
Esta tabla los mapea a sus nombres completos para mostrarlos en la UI.

Si un nombre no esta en la tabla, se devuelve el nombre original.
"""

FULL_NAMES: dict = {
    # ---- ENGLAND (Premier League / Championship) ----
    "Arsenal": "Arsenal FC",
    "Aston Villa": "Aston Villa FC",
    "Birmingham": "Birmingham City",
    "Blackburn": "Blackburn Rovers",
    "Blackpool": "Blackpool FC",
    "Bournemouth": "AFC Bournemouth",
    "Brentford": "Brentford FC",
    "Brighton": "Brighton & Hove Albion",
    "Bristol City": "Bristol City",
    "Burnley": "Burnley FC",
    "Cardiff": "Cardiff City",
    "Chelsea": "Chelsea FC",
    "Coventry": "Coventry City",
    "Crystal Palace": "Crystal Palace FC",
    "Derby": "Derby County",
    "Everton": "Everton FC",
    "Fulham": "Fulham FC",
    "Huddersfield": "Huddersfield Town",
    "Hull": "Hull City",
    "Ipswich": "Ipswich Town",
    "Leeds": "Leeds United",
    "Leicester": "Leicester City",
    "Liverpool": "Liverpool FC",
    "Luton": "Luton Town",
    "Man City": "Manchester City",
    "Man United": "Manchester United",
    "Middlesbrough": "Middlesbrough FC",
    "Millwall": "Millwall FC",
    "Newcastle": "Newcastle United",
    "Norwich": "Norwich City",
    "Nott'm Forest": "Nottingham Forest",
    "Peterboro": "Peterborough United",
    "Plymouth": "Plymouth Argyle",
    "Preston": "Preston North End",
    "QPR": "Queens Park Rangers",
    "Reading": "Reading FC",
    "Rotherham": "Rotherham United",
    "Sheff Utd": "Sheffield United",
    "Sheff Wed": "Sheffield Wednesday",
    "Sheffield Utd": "Sheffield United",
    "Southampton": "Southampton FC",
    "Stoke": "Stoke City",
    "Sunderland": "Sunderland AFC",
    "Swansea": "Swansea City",
    "Tottenham": "Tottenham Hotspur",
    "Watford": "Watford FC",
    "West Brom": "West Bromwich Albion",
    "West Ham": "West Ham United",
    "Wigan": "Wigan Athletic",
    "Wolves": "Wolverhampton Wanderers",
    "Wycombe": "Wycombe Wanderers",

    # ---- SPAIN (La Liga / Segunda) ----
    "Alaves": "Deportivo Alavés",
    "Almeria": "UD Almería",
    "Ath Bilbao": "Athletic Club Bilbao",
    "Ath Madrid": "Atlético de Madrid",
    "Barcelona": "FC Barcelona",
    "Betis": "Real Betis",
    "Cadiz": "Cádiz CF",
    "Celta": "Celta de Vigo",
    "Cordoba": "Córdoba CF",
    "Eibar": "SD Eibar",
    "Elche": "Elche CF",
    "Espanol": "RCD Espanyol",
    "Getafe": "Getafe CF",
    "Girona": "Girona FC",
    "Granada": "Granada CF",
    "Huesca": "SD Huesca",
    "La Coruna": "Deportivo La Coruña",
    "Las Palmas": "UD Las Palmas",
    "Leganes": "CD Leganés",
    "Levante": "Levante UD",
    "Mallorca": "RCD Mallorca",
    "Malaga": "Málaga CF",
    "Osasuna": "CA Osasuna",
    "Oviedo": "Real Oviedo",
    "Real Madrid": "Real Madrid CF",
    "Sevilla": "Sevilla FC",
    "Sociedad": "Real Sociedad",
    "Sp Gijon": "Sporting de Gijón",
    "Tenerife": "CD Tenerife",
    "Valencia": "Valencia CF",
    "Valladolid": "Real Valladolid",
    "Vallecano": "Rayo Vallecano",
    "Villarreal": "Villarreal CF",
    "Zaragoza": "Real Zaragoza",

    # ---- ITALY (Serie A / Serie B) ----
    "Atalanta": "Atalanta BC",
    "Benevento": "Benevento Calcio",
    "Bologna": "Bologna FC",
    "Brescia": "Brescia Calcio",
    "Cagliari": "Cagliari Calcio",
    "Chievo": "Chievo Verona",
    "Como": "Como 1907",
    "Cremonese": "US Cremonese",
    "Empoli": "Empoli FC",
    "Fiorentina": "ACF Fiorentina",
    "Frosinone": "Frosinone Calcio",
    "Genoa": "Genoa CFC",
    "Hellas Verona": "Hellas Verona",
    "Inter": "Inter de Milán",
    "Juventus": "Juventus FC",
    "Lazio": "SS Lazio",
    "Lecce": "US Lecce",
    "Milan": "AC Milan",
    "Monza": "AC Monza",
    "Napoli": "SSC Napoli",
    "Palermo": "Palermo FC",
    "Parma": "Parma Calcio 1913",
    "Pisa": "Pisa Sporting Club",
    "Roma": "AS Roma",
    "Salernitana": "US Salernitana 1919",
    "Sampdoria": "UC Sampdoria",
    "Sassuolo": "US Sassuolo",
    "Spal": "SPAL Ferrara",
    "Spezia": "Spezia Calcio",
    "Torino": "Torino FC",
    "Udinese": "Udinese Calcio",
    "Venezia": "Venezia FC",
    "Verona": "Hellas Verona",

    # ---- GERMANY (Bundesliga / 2. Bundesliga) ----
    "Augsburg": "FC Augsburg",
    "Bayern Munich": "Bayern München",
    "Bielefeld": "Arminia Bielefeld",
    "Bochum": "VfL Bochum",
    "Darmstadt": "SV Darmstadt 98",
    "Dortmund": "Borussia Dortmund",
    "Dusseldorf": "Fortuna Düsseldorf",
    "Ein Frankfurt": "Eintracht Frankfurt",
    "FC Koln": "1. FC Köln",
    "Freiburg": "SC Freiburg",
    "Greuther Furth": "SpVgg Greuther Fürth",
    "Hamburg": "Hamburger SV",
    "Hannover": "Hannover 96",
    "Hansa Rostock": "FC Hansa Rostock",
    "Heidenheim": "1. FC Heidenheim",
    "Hertha": "Hertha BSC Berlin",
    "Hoffenheim": "TSG 1899 Hoffenheim",
    "Holstein Kiel": "Holstein Kiel",
    "Karlsruhe": "Karlsruher SC",
    "Kaiserslautern": "1. FC Kaiserslautern",
    "Leverkusen": "Bayer 04 Leverkusen",
    "M'gladbach": "Borussia Mönchengladbach",
    "Mainz": "1. FSV Mainz 05",
    "Nurnberg": "1. FC Nürnberg",
    "Paderborn": "SC Paderborn 07",
    "RB Leipzig": "RB Leipzig",
    "Schalke 04": "FC Schalke 04",
    "St Pauli": "FC St. Pauli",
    "Stuttgart": "VfB Stuttgart",
    "Union Berlin": "1. FC Union Berlin",
    "Werder Bremen": "SV Werder Bremen",
    "Wolfsburg": "VfL Wolfsburg",

    # ---- FRANCE (Ligue 1 / Ligue 2) ----
    "Ajaccio": "AC Ajaccio",
    "Amiens": "Amiens SC",
    "Angers": "Angers SCO",
    "Auxerre": "AJ Auxerre",
    "Bordeaux": "FC Girondins de Bordeaux",
    "Brest": "Stade Brestois 29",
    "Caen": "Stade Malherbe Caen",
    "Clermont": "Clermont Foot 63",
    "Dijon": "Dijon FCO",
    "Guingamp": "EA Guingamp",
    "Le Havre": "Le Havre AC",
    "Lens": "RC Lens",
    "Lille": "LOSC Lille",
    "Lorient": "FC Lorient",
    "Lyon": "Olympique Lyonnais",
    "Marseille": "Olympique de Marseille",
    "Metz": "FC Metz",
    "Monaco": "AS Monaco",
    "Montpellier": "Montpellier HSC",
    "Nantes": "FC Nantes",
    "Nice": "OGC Nice",
    "Nimes": "Nîmes Olympique",
    "Paris SG": "Paris Saint-Germain",
    "Reims": "Stade de Reims",
    "Rennes": "Stade Rennais FC",
    "St Etienne": "AS Saint-Étienne",
    "Strasbourg": "RC Strasbourg Alsace",
    "Toulouse": "Toulouse FC",
    "Troyes": "ESTAC Troyes",

    # ---- NETHERLANDS (Eredivisie) ----
    "Ajax": "AFC Ajax",
    "AZ Alkmaar": "AZ Alkmaar",
    "Feyenoord": "Feyenoord Rotterdam",
    "PSV Eindhoven": "PSV Eindhoven",
    "Twente": "FC Twente",
    "Utrecht": "FC Utrecht",
    "Vitesse": "Vitesse Arnhem",

    # ---- PORTUGAL (Primeira Liga) ----
    "Benfica": "SL Benfica",
    "Braga": "SC Braga",
    "Porto": "FC Porto",
    "Sporting": "Sporting CP",
    "Sp Lisbon": "Sporting CP",
    "Estoril": "GD Estoril Praia",
    "Boavista": "Boavista FC",
    "Vitoria": "Vitória SC",
    "Pacos Ferreira": "FC Paços de Ferreira",
    "Famalicao": "FC Famalicão",
    "Maritimo": "CS Marítimo",

    # ---- BELGIUM (Pro League) ----
    "Anderlecht": "RSC Anderlecht",
    "Bruges": "Club Brugge KV",
    "Club Brugge": "Club Brugge KV",
    "Gent": "KAA Gent",
    "Genk": "KRC Genk",
    "Standard": "Standard Liège",
    "St. Gilloise": "Royale Union Saint-Gilloise",
    "Antwerp": "Royal Antwerp FC",
    "Charleroi": "Sporting Charleroi",
    "Mechelen": "KV Mechelen",
    "Cercle Brugge": "Cercle Brugge KSV",
    "St Truiden": "Sint-Truidense VV",

    # ---- TURKEY (Süper Lig) ----
    "Besiktas": "Beşiktaş JK",
    "Fenerbahce": "Fenerbahçe SK",
    "Galatasaray": "Galatasaray SK",
    "Trabzonspor": "Trabzonspor",
    "Konyaspor": "Konyaspor",
    "Sivasspor": "Sivasspor",
    "Adana Demirspor": "Adana Demirspor",
    "Basaksehir": "İstanbul Başakşehir",
    "Kasimpasa": "Kasımpaşa SK",

    # ---- GREECE (Super League) ----
    "Olympiakos": "Olympiacos FC",
    "AEK": "AEK Athens",
    "PAOK": "PAOK Salónica",
    "Panathinaikos": "Panathinaikos FC",
    "Aris": "Aris Salónica",
    "OFI Crete": "OFI Crete",

    # ---- SCOTLAND (Premiership) ----
    "Celtic": "Celtic FC",
    "Rangers": "Rangers FC",
    "Aberdeen": "Aberdeen FC",
    "Hearts": "Heart of Midlothian",
    "Hibernian": "Hibernian FC",
    "Motherwell": "Motherwell FC",
    "St Johnstone": "St. Johnstone FC",
    "Kilmarnock": "Kilmarnock FC",
    "Livingston": "Livingston FC",
    "Dundee Utd": "Dundee United",
    "St Mirren": "St. Mirren FC",

    # ---- MEXICO (Liga MX) ----
    "America": "Club América",
    "Guadalajara": "Chivas de Guadalajara",
    "Monterrey": "CF Monterrey",
    "Tigres": "Tigres UANL",
    "Cruz Azul": "Cruz Azul",
    "Pumas": "Pumas UNAM",
    "Toluca": "Deportivo Toluca",
    "Pachuca": "CF Pachuca",
    "León": "Club León",
    "Necaxa": "Club Necaxa",
    "Atlas": "Atlas FC",
    "Tijuana": "Club Tijuana",
    "Santos": "Santos Laguna",
    "Puebla": "Club Puebla",
    "Mazatlán": "Mazatlán FC",
    "Querétaro": "Querétaro FC",
    "Juárez": "FC Juárez",
    "San Luis": "Atlético de San Luis",

    # ---- USA (MLS) ----
    "LA Galaxy": "LA Galaxy",
    "LAFC": "Los Angeles FC",
    "Inter Miami": "Inter Miami CF",
    "Atlanta United": "Atlanta United FC",
    "Seattle": "Seattle Sounders",
    "Seattle Sounders": "Seattle Sounders",
    "Portland": "Portland Timbers",
    "Portland Timbers": "Portland Timbers",
    "NYC FC": "New York City FC",
    "New York City": "New York City FC",
    "NY Red Bulls": "New York Red Bulls",
    "New York Red Bulls": "New York Red Bulls",
    "Toronto FC": "Toronto FC",
    "DC United": "DC United",
    "Chicago Fire": "Chicago Fire FC",
    "Columbus Crew": "Columbus Crew",
    "FC Cincinnati": "FC Cincinnati",
    "Houston Dynamo": "Houston Dynamo",
    "FC Dallas": "FC Dallas",
    "Real Salt Lake": "Real Salt Lake",
    "Vancouver Whitecaps": "Vancouver Whitecaps",
    "Montreal Impact": "CF Montreal",
    "CF Montreal": "CF Montreal",
    "Minnesota United": "Minnesota United",
    "New England": "New England Revolution",
    "Philadelphia Union": "Philadelphia Union",
    "Orlando City": "Orlando City SC",
    "Sporting KC": "Sporting Kansas City",
    "San Jose": "San Jose Earthquakes",
    "Colorado": "Colorado Rapids",
    "Nashville": "Nashville SC",
    "St. Louis City": "St. Louis City SC",
    "Charlotte FC": "Charlotte FC",
    "Austin": "Austin FC",

    # ---- BRAZIL (Brasileirao) ----
    "Flamengo RJ": "CR Flamengo",
    "Flamengo": "CR Flamengo",
    "Palmeiras": "SE Palmeiras",
    "Corinthians": "SC Corinthians",
    "Sao Paulo": "São Paulo FC",
    "São Paulo": "São Paulo FC",
    "Fluminense": "Fluminense FC",
    "Botafogo RJ": "Botafogo FR",
    "Botafogo": "Botafogo FR",
    "Internacional": "SC Internacional",
    "Gremio": "Grêmio",
    "Grêmio": "Grêmio",
    "Atletico-MG": "Atlético Mineiro",
    "Atletico MG": "Atlético Mineiro",
    "Vasco": "CR Vasco da Gama",
    "Cruzeiro": "Cruzeiro EC",
    "Bahia": "EC Bahia",
    "Athletico-PR": "Athletico Paranaense",
    "Athletico PR": "Athletico Paranaense",
    "Santos": "Santos FC",
    "Bragantino": "RB Bragantino",
    "Fortaleza": "Fortaleza EC",
    "Ceará": "Ceará SC",
    "Cuiabá": "Cuiabá EC",
    "Goiás": "Goiás EC",
    "Coritiba": "Coritiba FC",
    "América-MG": "América Mineiro",
    "Vitória": "EC Vitória",
    "Juventude": "EC Juventude",
    "Mirassol": "Mirassol FC",

    # ---- ARGENTINA (Primera Division) ----
    "Boca Juniors": "CA Boca Juniors",
    "River Plate": "CA River Plate",
    "Independiente": "CA Independiente",
    "Racing Club": "Racing Club",
    "San Lorenzo": "CA San Lorenzo",
    "Velez Sarsfield": "CA Vélez Sarsfield",
    "Estudiantes": "Estudiantes de La Plata",
    "Lanus": "Club Atlético Lanús",
    "Banfield": "CA Banfield",
    "Newell's Old Boys": "Newell's Old Boys",
    "Rosario Central": "Rosario Central",
    "Talleres Cordoba": "CA Talleres",
    "Argentinos Juniors": "Argentinos Juniors",
    "Defensa y Justicia": "Defensa y Justicia",
    "Tigre": "CA Tigre",
    "Huracan": "CA Huracán",
    "Godoy Cruz": "Godoy Cruz",
    "Gimnasia LP": "Gimnasia La Plata",
    "Colon Santa Fe": "CA Colón",
    "Union Santa Fe": "CA Unión",
    "Belgrano Cordoba": "CA Belgrano",
    "Platense": "Platense",
    "Instituto": "Instituto AC Córdoba",

    # ---- POLAND (Ekstraklasa) ----
    "Legia Warsaw": "Legia Warszawa",
    "Lech Poznan": "Lech Poznań",
    "Pogon Szczecin": "Pogoń Szczecin",
    "Slask Wroclaw": "Śląsk Wrocław",
    "Cracovia": "MKS Cracovia",
    "Wisla Krakow": "Wisła Kraków",
    "Rakow": "Raków Częstochowa",
    "Jagiellonia": "Jagiellonia Białystok",
    "Lechia Gdansk": "Lechia Gdańsk",
    "Gornik Zabrze": "Górnik Zabrze",

    # ---- ROMANIA (Liga 1) ----
    "FCSB": "FCSB",
    "CFR Cluj": "CFR 1907 Cluj",
    "U Craiova": "Universitatea Craiova",
    "Univ Craiova": "Universitatea Craiova",
    "Rapid Bucuresti": "FC Rapid București",
    "Sepsi": "Sepsi OSK",
    "Hermannstadt": "FC Hermannstadt",

    # ---- SWEDEN (Allsvenskan) ----
    "Malmo FF": "Malmö FF",
    "AIK": "AIK Solna",
    "Hammarby": "Hammarby IF",
    "Djurgardens": "Djurgårdens IF",
    "IFK Goteborg": "IFK Göteborg",
    "Elfsborg": "IF Elfsborg",
    "Hacken": "BK Häcken",
    "Norrkoping": "IFK Norrköping",
    "Mjallby": "Mjällby AIF",

    # ---- NORWAY (Eliteserien) ----
    "Bodo/Glimt": "FK Bodø/Glimt",
    "Molde": "Molde FK",
    "Rosenborg": "Rosenborg BK",
    "Brann": "SK Brann",
    "Viking": "Viking FK",
    "Lillestrom": "Lillestrøm SK",
    "Stromsgodset": "Strømsgodset IF",
    "Valerenga": "Vålerenga IF",

    # ---- JAPAN (J1 League) ----
    "Kashima Antlers": "Kashima Antlers",
    "Urawa Red Diamonds": "Urawa Red Diamonds",
    "Yokohama F. Marinos": "Yokohama F. Marinos",
    "Kawasaki Frontale": "Kawasaki Frontale",
    "Vissel Kobe": "Vissel Kobe",
    "Nagoya Grampus": "Nagoya Grampus",
    "FC Tokyo": "FC Tokyo",
    "Sanfrecce Hiroshima": "Sanfrecce Hiroshima",
    "Cerezo Osaka": "Cerezo Osaka",
    "Gamba Osaka": "Gamba Osaka",

    # ---- CHINA (Super League) ----
    "Beijing Guoan": "Beijing Guoan",
    "Shanghai SIPG": "Shanghai Port",
    "Shanghai Port": "Shanghai Port",
    "Shanghai Shenhua": "Shanghai Shenhua",
    "Shandong Taishan": "Shandong Taishan",
    "Guangzhou Evergrande": "Guangzhou FC",
    "Wuhan Three Towns": "Wuhan Three Towns",
}


def to_full(short_name: str) -> str:
    """Devuelve el nombre completo si esta en la tabla; si no, el original."""
    return FULL_NAMES.get(short_name, short_name)
